FROM public.ecr.aws/lambda/python:3.9 

COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt

RUN yum install -y gnupg2 && yum clean all
    
COPY decrypt_pgp_files.py ${LAMBDA_TASK_ROOT}

CMD [ "decrypt_pgp_files.handler" ]